---
minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["-f=lf"]
      - id: check-added-large-files

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.3.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: ["--write", "--ignore-unknown"] # this will format files in place
        exclude: '\.git'
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
    -   id: eslint
        files: ^src/.*\.ts$  # Match only TypeScript files in the src/ directory
        types: [file]
