name: 'DangerJS Action'
description: 'Run DangerJS'

inputs:
  max-commits-enabled:
    description: 'Enabled rule for Maximum number of commits in PR'
    required: false
  max-commits-info:
    description: 'Maximum number of commits in PR (throw MESSAGE)'
    required: false
  max-commits-warn:
    description: 'Maximum number of commits in PR (throw WARN)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ENABLE_CHECK_MR_TOO_MANY_COMMITS: ${{ inputs.max-commits-enabled }}
    MAX_COMMITS: ${{ inputs.max-commits-info }}
    MAX_COMMITS_WARN: ${{ inputs.max-commits-warn }}
