name: Codebase-Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [ master ]


jobs:
  codebase-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --no-progress --no-update-notifier

    - name: Run tests
      run: npm test

    - name: Publish Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: junit-report
        path: reports/report.xml
